#!/bin/bash

# install additional pythonlibs

pip install feedparser
pip install Elasticsearch
pip install BeautifulSoup4
pip install lxml
pip install xmljson 
pip install simplejson 
pip install html5lib
