#!/usr/bin/env python2
# -- coding: utf-8 --

#minimal but efficent newsreader
import locale
import feedparser
from elasticsearch import Elasticsearch
import time
import re
import requests
from bs4 import BeautifulSoup
readarticles = {}

locale.setlocale(locale.LC_ALL, 'en_GB.UTF-8')
d = feedparser.parse('http://www.investegate.co.uk/rss.aspx')
print(d.feed.title)
print(d.feed.link)
print(d.feed.description)
for i in d.entries:
  try: 
    if readarticles[i.link] > 0:
      next 
  except: 
    None
  timestamp = time.strftime('%Y-%m-%dT%H:%M:%SZ', i.published_parsed) 
  page=requests.get(i.link)
  readarticles[i.link]=1
  msgid = i.link.split('=')[1]
  rnstype = i.title.split(':')[1].strip().strip('/')
  soup = BeautifulSoup(page.content, 'lxml')
  article = soup.find(id="ArticleContent")
  print(timestamp, i.investegate_companycode, rnstype)
  doc = { 
          'timestamp' : timestamp,
          'EPIC' : i.investegate_companycode.strip('(').strip(')'),
          'title' : i.title, 
          'url' : i.link, 
          'rnsbody' : article,
  }
  fh = open("./news/"+msgid,"w")
  fh.write(article.prettify().encode('ascii', 'ignore') )
  fh.close() 
  #print(doc)
  #print(readarticles)
